<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="coverlet.collector" Version="6.0.2"/>
        <PackageVersion Include="Docker.DotNet" Version="3.125.15" />
        <PackageVersion Include="FluentFTP" Version="50.1.0" />
        <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageVersion Include="Moq" Version="4.20.70" />
        <PackageVersion Include="NetCoreServer" Version="8.0.7" />
        <PackageVersion Include="xunit.v3" Version="0.7.0-pre.15"/>
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.0.0-pre.49"/>
    </ItemGroup>
</Project>
